name: Unit Tests CI/CD

on: [push]

jobs:
  ubuntu-tests:
    name: Tests on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run unit tests
        run: python -m unittest discover ./tests/ -p '*_test.py'

  windows-tests:
    name: Tests on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run unit tests
        run: python -m unittest discover ./tests/ -p '*_test.py'
